USE [master]
GO

/****** Object:  Database [EdgerUser]    Script Date: 02/03/2018 4:51:21 PM ******/
CREATE DATABASE [EdgerUser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EdgerUser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\EdgerUser.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EdgerUser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\EdgerUser.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [EdgerUser] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EdgerUser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EdgerUser] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [EdgerUser] SET ANSI_NULLS ON 
GO

ALTER DATABASE [EdgerUser] SET ANSI_PADDING ON 
GO

ALTER DATABASE [EdgerUser] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [EdgerUser] SET ARITHABORT ON 
GO

ALTER DATABASE [EdgerUser] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EdgerUser] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [EdgerUser] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EdgerUser] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EdgerUser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EdgerUser] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [EdgerUser] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [EdgerUser] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EdgerUser] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [EdgerUser] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EdgerUser] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EdgerUser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EdgerUser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EdgerUser] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EdgerUser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EdgerUser] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EdgerUser] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EdgerUser] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EdgerUser] SET RECOVERY FULL 
GO

ALTER DATABASE [EdgerUser] SET  MULTI_USER 
GO

ALTER DATABASE [EdgerUser] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EdgerUser] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EdgerUser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EdgerUser] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EdgerUser] SET  READ_WRITE 
GO

