USE [master]
GO

/****** Object:  Database [ResourceEdgePublish]    Script Date: 02/03/2018 4:51:06 PM ******/
CREATE DATABASE [ResourceEdgePublish]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ResourceEdgePublish', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\ResourceEdgePublish.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ResourceEdgePublish_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS2012\MSSQL\DATA\ResourceEdgePublish.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ResourceEdgePublish] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ResourceEdgePublish].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ResourceEdgePublish] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET ANSI_NULLS ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET ANSI_PADDING ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET ARITHABORT ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [ResourceEdgePublish] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [ResourceEdgePublish] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ResourceEdgePublish] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ResourceEdgePublish] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET RECOVERY FULL 
GO

ALTER DATABASE [ResourceEdgePublish] SET  MULTI_USER 
GO

ALTER DATABASE [ResourceEdgePublish] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ResourceEdgePublish] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ResourceEdgePublish] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ResourceEdgePublish] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ResourceEdgePublish] SET  READ_WRITE 
GO

