//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceEdge.Domain.DbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sentrifugoDBEntities : DbContext
    {
        public sentrifugoDBEntities()
            : base("name=sentrifugoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<main_pa_appraisalhistory> main_pa_appraisalhistory { get; set; }
        public virtual DbSet<main_pa_category> main_pa_category { get; set; }
        public virtual DbSet<main_pa_employee_ratings> main_pa_employee_ratings { get; set; }
        public virtual DbSet<main_pa_ff_employee_ratings> main_pa_ff_employee_ratings { get; set; }
        public virtual DbSet<main_pa_questions> main_pa_questions { get; set; }
        public virtual DbSet<main_pa_questions_privileges> main_pa_questions_privileges { get; set; }
        public virtual DbSet<main_pa_ratings> main_pa_ratings { get; set; }
        public virtual DbSet<main_pa_skills> main_pa_skills { get; set; }
    }
}
