//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceEdge.Domain.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_pa_questions_privileges
    {
        public int id { get; set; }
        public Nullable<int> pa_initialization_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string hr_qs { get; set; }
        public string hr_group_qs_privileges { get; set; }
        public Nullable<int> manager_group_id { get; set; }
        public string manager_qs { get; set; }
        public string manager_qs_privileges { get; set; }
        public string ff_qs { get; set; }
        public string ff_qs_privileges { get; set; }
        public Nullable<bool> module_flag { get; set; }
        public Nullable<int> line_manager_1 { get; set; }
        public Nullable<int> line_manager_2 { get; set; }
        public Nullable<int> line_manager_3 { get; set; }
        public Nullable<int> line_manager_4 { get; set; }
        public Nullable<int> line_manager_5 { get; set; }
        public Nullable<bool> manager_levels { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> createdby_role { get; set; }
        public Nullable<int> createdby_group { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<int> modifiedby_role { get; set; }
        public Nullable<int> modifiedby_group { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
