//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceEdge.Domain.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_pa_employee_ratings
    {
        public int id { get; set; }
        public Nullable<int> pa_initialization_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string employee_response { get; set; }
        public string manager_response { get; set; }
        public string skill_response { get; set; }
        public Nullable<int> line_manager_1 { get; set; }
        public Nullable<int> line_manager_2 { get; set; }
        public Nullable<int> line_manager_3 { get; set; }
        public Nullable<int> line_manager_4 { get; set; }
        public Nullable<int> line_manager_5 { get; set; }
        public string line_comment_1 { get; set; }
        public string line_comment_2 { get; set; }
        public string line_comment_3 { get; set; }
        public string line_comment_4 { get; set; }
        public string line_comment_5 { get; set; }
        public Nullable<int> line_rating_1 { get; set; }
        public Nullable<int> line_rating_2 { get; set; }
        public Nullable<int> line_rating_3 { get; set; }
        public Nullable<int> line_rating_4 { get; set; }
        public Nullable<int> line_rating_5 { get; set; }
        public Nullable<double> consolidated_rating { get; set; }
        public string appraisal_status { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> createdby_role { get; set; }
        public Nullable<int> createdby_group { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<int> modifiedby_role { get; set; }
        public Nullable<int> modifiedby_group { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public Nullable<System.DateTime> modifieddate { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
