//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceEdge.Domain.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class main_requisition_summary
    {
        public int id { get; set; }
        public Nullable<int> req_id { get; set; }
        public string requisition_code { get; set; }
        public Nullable<System.DateTime> onboard_date { get; set; }
        public Nullable<int> position_id { get; set; }
        public string position_name { get; set; }
        public Nullable<int> reporting_id { get; set; }
        public string reporting_manager_name { get; set; }
        public Nullable<int> businessunit_id { get; set; }
        public string businessunit_name { get; set; }
        public Nullable<int> department_id { get; set; }
        public string department_name { get; set; }
        public Nullable<int> jobtitle { get; set; }
        public string jobtitle_name { get; set; }
        public Nullable<int> req_no_positions { get; set; }
        public Nullable<int> selected_members { get; set; }
        public Nullable<int> filled_positions { get; set; }
        public string jobdescription { get; set; }
        public string req_skills { get; set; }
        public string req_qualification { get; set; }
        public string req_exp_years { get; set; }
        public Nullable<int> emp_type { get; set; }
        public string emp_type_name { get; set; }
        public Nullable<bool> req_priority { get; set; }
        public string additional_info { get; set; }
        public string req_status { get; set; }
        public Nullable<int> approver1 { get; set; }
        public string approver1_name { get; set; }
        public Nullable<int> approver2 { get; set; }
        public string approver2_name { get; set; }
        public Nullable<int> approver3 { get; set; }
        public string approver3_name { get; set; }
        public string appstatus1 { get; set; }
        public string appstatus2 { get; set; }
        public string appstatus3 { get; set; }
        public string recruiters { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string createdby_name { get; set; }
        public Nullable<int> createdby { get; set; }
        public Nullable<int> modifiedby { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public Nullable<System.DateTime> modifiedon { get; set; }
    }
}
