//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace resourceEdge.Domain.DbEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sentrifugoDBEntities2 : DbContext
    {
        public sentrifugoDBEntities2()
            : base("name=sentrifugoDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<main_request_history> main_request_history { get; set; }
        public virtual DbSet<main_requisition> main_requisition { get; set; }
        public virtual DbSet<main_requisition_history> main_requisition_history { get; set; }
        public virtual DbSet<main_requisition_summary> main_requisition_summary { get; set; }
    }
}
