// <auto-generated />
namespace resourceEdge.Domain.Migrations.EdgeDbContext2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AssetAssetCategoryandRequestAssetgroupandlocationUpdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssetAssetCategoryandRequestAssetgroupandlocationUpdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201805081200268_Asset,AssetCategory and RequestAsset group and location Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
