// <auto-generated />
namespace resourceEdge.webUi.Migrations.ApplicationDbConntextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IdentitymodelupdatedwithnullablegroupandlocationId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IdentitymodelupdatedwithnullablegroupandlocationId));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081202338_Identity model updated with nullable group and location Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
